### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Ashymad** [SpringsStudio/Bortz#1]
- [ ] Engine
  - [x] Basic game functionality
    - [x] Piece movement
    - [x] Piece capture
  - [ ] Basic game logic
    - [x] Chick -> Chicken change after end row reached
    - [x] Win after capturing opponent's lion piece
    - [x] Win after reaching the end row with a lion piece if not in danger
    - [ ] Draw after 3-turn move repetition
- [x] Engine -> UI communication
  - [x] Rewrite protocol to adhere to [shogi notation](https://en.wikipedia.org/wiki/Shogi_notation)
- [ ] Game types
  - [ ] VS Friend
  - [x] VS AI
    - [x] Random Ai
    - [x] Minimax Ai
    - [ ] Difficulty setting
  - [ ] Online
    - [ ] Server?
  - [ ] Replay
    - [ ] Online replays
    - [ ] Past Games
    - [ ] "Play from here" option
- [ ] UI
  - [ ] Main Menu
  - [ ] Training Menu
  - [ ] Credits
  - [x] Options
    - [x] Theme chooser
    - [x] Guides switch
    - [x] Saving to [preferences](https://developer.android.com/training/basics/data-storage/shared-preferences.html)
  - [ ] Game Screen
     - [x] Board
     - [x] Captured Pieces
     - [ ] Timer/Username
     - [ ] Win dialog
     - [x] [Animations](https://stackoverflow.com/questions/4689918/how-to-move-an-image-from-left-to-right-in-android)
  - [ ] Themes
    - [x] Loading from [preferences](https://developer.android.com/training/basics/data-storage/shared-preferences.html)
    - [x] Guides
    - [x] Animal kanji theme
    - [x] Chess-like theme
    - [ ] Animal theme
    - [ ] Shogi theme
- [ ] Test
  - [x] Create tests for GameEngine methods
  - [ ] ...
- [x] Misc
  - [x] Create README
